# -*- coding: utf-8 -*-
"""Esports_Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n24gxFqqSN0MPK_4_Od697CsCHGHVOQY
"""

import polars as pl

from google.colab import drive
drive.mount('/content/drive')

file_path = "/content/drive/MyDrive/Esports_project/2026_LoL_esports_match_data_from_OraclesElixir.csv"

df = pl.read_csv(file_path)

print(df.shape)
df.head()

print(df.columns)

#count how many times each "position" appears
df["position"].value_counts()

### Analysis
# top, jng, mid, bot, sup = positions in a team
# a full match = 2 teams = 6x2 rows = 12 rows per match
# 9184 team rows -> 4592 matches

## split the dataset into two smaller datasets - player rows & team rows
# copy() -> does not affect original dataset

players = df.filter(pl.col("position") != "team")
teams   = df.filter(pl.col("position") == "team")

## check is split worked correctly:
# df.shape -> show (num of rows, num of cols)
print("Player rows:", players.shape)
print("Team rows:", teams.shape)

# champion win rates
champ_wr = (
    players
    .group_by("champion")
    .agg([
        pl.col("result").mean().alias("win_rate"),
        pl.len().alias("games")
    ])
    .filter(pl.col("games") >= 10)
    .sort("win_rate", descending=True)
)

print(champ_wr.head(15))

#champion pain synergy - which two champions win more tgt?
#Join every champion against teammates in the same game.

pairs = (
    players.select(["gameid","teamname","champion","result"])
    .join(
        players.select(["gameid","teamname","champion"])
               .rename({"champion": "champ2"}),
        on=["gameid","teamname"]
    )
    .filter(pl.col("champion") < pl.col("champ2"))
    .group_by(["champion","champ2"])
    .agg([
        pl.col("result").mean().alias("pair_win_rate"),
        pl.len().alias("games_together")
    ])
    .filter(pl.col("games_together") >= 5)
    .sort("pair_win_rate", descending=True)
)

print(pairs.head(15))

# trim to draft column (still 55000 rows)
draft_base = players.select([
    "gameid", "league", "year", "split",
    "playoffs", "date", "patch",
    "side", "position", "teamname",
    "firstPick", "champion",
    "ban1", "ban2", "ban3", "ban4", "ban5",
    "result"
])

print(f"Columns: {draft_base.shape[1]}")
print(f"Rows: {draft_base.shape[0]}")
print(draft_base.head(5))

# Create clean column names like blue_top, red_jng, blue_mid
draft_with_role = draft_base.with_columns(
    (
        pl.col("side").str.to_lowercase()
        + "_"
        + pl.col("position")
    ).alias("side_position")
)

champion_pivot = (
    draft_with_role
    .select(["gameid", "side_position", "champion"])
    .pivot(
        values="champion",
        index="gameid",
        on="side_position",
        aggregate_function="first"
    )
)

print(champion_pivot.head(5))
print(champion_pivot.columns)

# Get one row per game for general match information
game_context = (
    draft_base
    .group_by("gameid")
    .agg([
        pl.col("league").first(),
        pl.col("year").first(),
        pl.col("split").first(),
        pl.col("playoffs").first(),
        pl.col("date").first(),
        pl.col("patch").first()
    ])
)

print(game_context.head(5))

# Get one representative row per game per side
side_info = (
    draft_base
    .group_by(["gameid", "side"])
    .agg([
        pl.col("teamname").first(),
        pl.col("firstPick").first(),
        pl.col("ban1").first(),
        pl.col("ban2").first(),
        pl.col("ban3").first(),
        pl.col("ban4").first(),
        pl.col("ban5").first()
    ])
)

blue_info = (
    side_info
    .filter(pl.col("side") == "Blue")
    .select([
        "gameid",
        pl.col("teamname").alias("blue_team"),
        pl.col("firstPick").alias("blue_firstPick"),
        pl.col("ban1").alias("blue_ban1"),
        pl.col("ban2").alias("blue_ban2"),
        pl.col("ban3").alias("blue_ban3"),
        pl.col("ban4").alias("blue_ban4"),
        pl.col("ban5").alias("blue_ban5")
    ])
)

red_info = (
    side_info
    .filter(pl.col("side") == "Red")
    .select([
        "gameid",
        pl.col("teamname").alias("red_team"),
        pl.col("firstPick").alias("red_firstPick"),
        pl.col("ban1").alias("red_ban1"),
        pl.col("ban2").alias("red_ban2"),
        pl.col("ban3").alias("red_ban3"),
        pl.col("ban4").alias("red_ban4"),
        pl.col("ban5").alias("red_ban5")
    ])
)

print(blue_info.head(3))
print(red_info.head(3))

# Get Blue side's result as the model target
blue_results = (
    teams
    .filter(pl.col("side") == "Blue")
    .select([
        "gameid",
        pl.col("result").alias("blue_win")
    ])
)

print(blue_results.head(5))

final_draft = (
    champion_pivot
    .join(game_context, on="gameid", how="left")
    .join(blue_info, on="gameid", how="left")
    .join(red_info, on="gameid", how="left")
    .join(blue_results, on="gameid", how="left")
)

print(final_draft.shape)
print(final_draft.head(5))
print(final_draft.columns)

print("Unique games in draft_base:", draft_base["gameid"].n_unique())
print("Rows in final_draft:", final_draft.shape[0])

print(final_draft["blue_win"].value_counts())
print(final_draft.null_count())

output_dir = "/content/drive/MyDrive/Esports_project"

final_draft.write_parquet(f"{output_dir}/final_draft.parquet")
champ_wr.write_parquet(f"{output_dir}/champ_winrates.parquet")
pairs.write_parquet(f"{output_dir}/champ_synergies.parquet")
players.write_parquet(f"{output_dir}/players.parquet")
teams.write_parquet(f"{output_dir}/teams.parquet")

print("Done! Parquet files saved to Google Drive.")